#!/usr/bin/env swift
//
// generate_obfuscated_key.swift
//
// Generates XOR-obfuscated byte arrays for embedding an API key in source code.
//
// Usage:
//   swift Scripts/generate_obfuscated_key.swift "YOUR_API_KEY"
//
// Paste the output into EmbeddedAPIKey.swift.

import Foundation
import Security

guard CommandLine.arguments.count == 2 else {
    fputs("Usage: swift \(CommandLine.arguments[0]) \"YOUR_API_KEY\"\n", stderr)
    exit(1)
}

let key = CommandLine.arguments[1]
let keyBytes = Array(key.utf8)

guard !keyBytes.isEmpty else {
    fputs("Error: API key must not be empty.\n", stderr)
    exit(1)
}

// Generate cryptographically random mask bytes.
var mask = [UInt8](repeating: 0, count: keyBytes.count)
let status = SecRandomCopyBytes(kSecRandomDefault, mask.count, &mask)
guard status == errSecSuccess else {
    fputs("Error: SecRandomCopyBytes failed with status \(status).\n", stderr)
    exit(1)
}

// XOR key with mask to produce obfuscated bytes.
let obfuscated = zip(keyBytes, mask).map { $0 ^ $1 }

func formatArray(_ bytes: [UInt8]) -> String {
    let hex = bytes.map { String(format: "0x%02X", $0) }
    // Wrap at 12 items per line for readability.
    var lines: [String] = []
    for start in stride(from: 0, to: hex.count, by: 12) {
        let end = min(start + 12, hex.count)
        lines.append("        " + hex[start..<end].joined(separator: ", "))
    }
    return lines.joined(separator: ",\n")
}

print("""
    // Generated by generate_obfuscated_key.swift — do not edit by hand.
    private static let obfuscated: [UInt8] = [
\(formatArray(obfuscated))
    ]

    private static let mask: [UInt8] = [
\(formatArray(mask))
    ]
""")
